site_name: InternshipReport

pages:
- Home: index.md
- ARTbio: artbio.md
- Introduction: 
   - Introduction: introduction.md
   - Galaxy: intro/galaxy.md
   - Metavisitor: metavisitor.md
   - Reference database: intro/vir1.md
- Materials and Methods: 
   - Viral sequences reference: matandmet/entrezquery.md
   - Cluster softwares: matandmet/cluster.md
   - Galaxy workflow: matandmet/workflow.md
   - Shell script: matandmet/shell_script.md
   - Testing 'vir2': matandmet/test.md 
- Results: results.md
- Discussion: discussion.md
- Conclusion: conclusion.md

theme: readthedocs
